apiVersion: v1
kind: Service
metadata:
  name: &name jellyseerr
  namespace: homelab
spec:
  type: ClusterIP
  ports:
    - name: *name
      port: 5055
      targetPort: 5055
  selector:
    app: *name
