# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - infisical run --env=prod --projectId=201b912b-40de-44bf-bb83-ab1bc77554b7 -- terraform apply -auto-approve
      - terraform output -raw kubeconfig > ../kubeconfig
      - terraform output -raw talosconfig > ../talosconfig
      - helmfile init
      - helmfile apply
      - cilium status --wait
      - |
        infisical run --env=prod --projectId=201b912b-40de-44bf-bb83-ab1bc77554b7 -- flux bootstrap github \
          --context=admin@hoopa \
          --owner=navaneeth-dev \
          --repository=fluxcd-homelab \
          --branch=main \
          --personal \
          --path=k8s/clusters/sp
    silent: true
