// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getClusterKubeconfig(args: GetClusterKubeconfigArgs, opts?: pulumi.InvokeOptions): Promise<GetClusterKubeconfigResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("talos:index/getClusterKubeconfig:getClusterKubeconfig", {
        "clientConfiguration": args.clientConfiguration,
        "endpoint": args.endpoint,
        "node": args.node,
        "timeouts": args.timeouts,
        "wait": args.wait,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getClusterKubeconfig.
 */
export interface GetClusterKubeconfigArgs {
    clientConfiguration: inputs.GetClusterKubeconfigClientConfiguration;
    endpoint?: string;
    node: string;
    timeouts?: inputs.GetClusterKubeconfigTimeouts;
    /**
     * @deprecated Deprecated
     */
    wait?: boolean;
}

/**
 * A collection of values returned by getClusterKubeconfig.
 */
export interface GetClusterKubeconfigResult {
    readonly clientConfiguration: outputs.GetClusterKubeconfigClientConfiguration;
    readonly endpoint: string;
    readonly id: string;
    readonly kubeconfigRaw: string;
    readonly kubernetesClientConfiguration: outputs.GetClusterKubeconfigKubernetesClientConfiguration;
    readonly node: string;
    readonly timeouts?: outputs.GetClusterKubeconfigTimeouts;
    /**
     * @deprecated Deprecated
     */
    readonly wait?: boolean;
}
export function getClusterKubeconfigOutput(args: GetClusterKubeconfigOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetClusterKubeconfigResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("talos:index/getClusterKubeconfig:getClusterKubeconfig", {
        "clientConfiguration": args.clientConfiguration,
        "endpoint": args.endpoint,
        "node": args.node,
        "timeouts": args.timeouts,
        "wait": args.wait,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getClusterKubeconfig.
 */
export interface GetClusterKubeconfigOutputArgs {
    clientConfiguration: pulumi.Input<inputs.GetClusterKubeconfigClientConfigurationArgs>;
    endpoint?: pulumi.Input<string>;
    node: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.GetClusterKubeconfigTimeoutsArgs>;
    /**
     * @deprecated Deprecated
     */
    wait?: pulumi.Input<boolean>;
}
