// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getClientConfiguration(args: GetClientConfigurationArgs, opts?: pulumi.InvokeOptions): Promise<GetClientConfigurationResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("talos:index/getClientConfiguration:getClientConfiguration", {
        "clientConfiguration": args.clientConfiguration,
        "clusterName": args.clusterName,
        "endpoints": args.endpoints,
        "nodes": args.nodes,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getClientConfiguration.
 */
export interface GetClientConfigurationArgs {
    clientConfiguration: inputs.GetClientConfigurationClientConfiguration;
    clusterName: string;
    endpoints?: string[];
    nodes?: string[];
}

/**
 * A collection of values returned by getClientConfiguration.
 */
export interface GetClientConfigurationResult {
    readonly clientConfiguration: outputs.GetClientConfigurationClientConfiguration;
    readonly clusterName: string;
    readonly endpoints?: string[];
    readonly id: string;
    readonly nodes?: string[];
    readonly talosConfig: string;
}
export function getClientConfigurationOutput(args: GetClientConfigurationOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetClientConfigurationResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("talos:index/getClientConfiguration:getClientConfiguration", {
        "clientConfiguration": args.clientConfiguration,
        "clusterName": args.clusterName,
        "endpoints": args.endpoints,
        "nodes": args.nodes,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getClientConfiguration.
 */
export interface GetClientConfigurationOutputArgs {
    clientConfiguration: pulumi.Input<inputs.GetClientConfigurationClientConfigurationArgs>;
    clusterName: pulumi.Input<string>;
    endpoints?: pulumi.Input<pulumi.Input<string>[]>;
    nodes?: pulumi.Input<pulumi.Input<string>[]>;
}
