// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getImageFactoryOverlaysVersions(args: GetImageFactoryOverlaysVersionsArgs, opts?: pulumi.InvokeOptions): Promise<GetImageFactoryOverlaysVersionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("talos:index/getImageFactoryOverlaysVersions:getImageFactoryOverlaysVersions", {
        "filters": args.filters,
        "talosVersion": args.talosVersion,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getImageFactoryOverlaysVersions.
 */
export interface GetImageFactoryOverlaysVersionsArgs {
    filters?: inputs.GetImageFactoryOverlaysVersionsFilters;
    talosVersion: string;
}

/**
 * A collection of values returned by getImageFactoryOverlaysVersions.
 */
export interface GetImageFactoryOverlaysVersionsResult {
    readonly filters?: outputs.GetImageFactoryOverlaysVersionsFilters;
    readonly id: string;
    readonly overlaysInfos: outputs.GetImageFactoryOverlaysVersionsOverlaysInfo[];
    readonly talosVersion: string;
}
export function getImageFactoryOverlaysVersionsOutput(args: GetImageFactoryOverlaysVersionsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetImageFactoryOverlaysVersionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("talos:index/getImageFactoryOverlaysVersions:getImageFactoryOverlaysVersions", {
        "filters": args.filters,
        "talosVersion": args.talosVersion,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getImageFactoryOverlaysVersions.
 */
export interface GetImageFactoryOverlaysVersionsOutputArgs {
    filters?: pulumi.Input<inputs.GetImageFactoryOverlaysVersionsFiltersArgs>;
    talosVersion: pulumi.Input<string>;
}
