// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getImageFactoryExtensionsVersions(args: GetImageFactoryExtensionsVersionsArgs, opts?: pulumi.InvokeOptions): Promise<GetImageFactoryExtensionsVersionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("talos:index/getImageFactoryExtensionsVersions:getImageFactoryExtensionsVersions", {
        "filters": args.filters,
        "talosVersion": args.talosVersion,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getImageFactoryExtensionsVersions.
 */
export interface GetImageFactoryExtensionsVersionsArgs {
    filters?: inputs.GetImageFactoryExtensionsVersionsFilters;
    talosVersion: string;
}

/**
 * A collection of values returned by getImageFactoryExtensionsVersions.
 */
export interface GetImageFactoryExtensionsVersionsResult {
    readonly extensionsInfos: outputs.GetImageFactoryExtensionsVersionsExtensionsInfo[];
    readonly filters?: outputs.GetImageFactoryExtensionsVersionsFilters;
    readonly id: string;
    readonly talosVersion: string;
}
export function getImageFactoryExtensionsVersionsOutput(args: GetImageFactoryExtensionsVersionsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetImageFactoryExtensionsVersionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("talos:index/getImageFactoryExtensionsVersions:getImageFactoryExtensionsVersions", {
        "filters": args.filters,
        "talosVersion": args.talosVersion,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getImageFactoryExtensionsVersions.
 */
export interface GetImageFactoryExtensionsVersionsOutputArgs {
    filters?: pulumi.Input<inputs.GetImageFactoryExtensionsVersionsFiltersArgs>;
    talosVersion: pulumi.Input<string>;
}
