// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getImageFactoryVersions(args?: GetImageFactoryVersionsArgs, opts?: pulumi.InvokeOptions): Promise<GetImageFactoryVersionsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("talos:index/getImageFactoryVersions:getImageFactoryVersions", {
        "filters": args.filters,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getImageFactoryVersions.
 */
export interface GetImageFactoryVersionsArgs {
    filters?: inputs.GetImageFactoryVersionsFilters;
}

/**
 * A collection of values returned by getImageFactoryVersions.
 */
export interface GetImageFactoryVersionsResult {
    readonly filters?: outputs.GetImageFactoryVersionsFilters;
    readonly id: string;
    readonly talosVersions: string[];
}
export function getImageFactoryVersionsOutput(args?: GetImageFactoryVersionsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetImageFactoryVersionsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("talos:index/getImageFactoryVersions:getImageFactoryVersions", {
        "filters": args.filters,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getImageFactoryVersions.
 */
export interface GetImageFactoryVersionsOutputArgs {
    filters?: pulumi.Input<inputs.GetImageFactoryVersionsFiltersArgs>;
}
