// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getMachineDisks(args: GetMachineDisksArgs, opts?: pulumi.InvokeOptions): Promise<GetMachineDisksResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("talos:index/getMachineDisks:getMachineDisks", {
        "clientConfiguration": args.clientConfiguration,
        "endpoint": args.endpoint,
        "filters": args.filters,
        "node": args.node,
        "timeouts": args.timeouts,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getMachineDisks.
 */
export interface GetMachineDisksArgs {
    clientConfiguration: inputs.GetMachineDisksClientConfiguration;
    endpoint?: string;
    filters?: inputs.GetMachineDisksFilters;
    node: string;
    timeouts?: inputs.GetMachineDisksTimeouts;
}

/**
 * A collection of values returned by getMachineDisks.
 */
export interface GetMachineDisksResult {
    readonly clientConfiguration: outputs.GetMachineDisksClientConfiguration;
    readonly disks: outputs.GetMachineDisksDisk[];
    readonly endpoint: string;
    readonly filters?: outputs.GetMachineDisksFilters;
    readonly id: string;
    readonly node: string;
    readonly timeouts?: outputs.GetMachineDisksTimeouts;
}
export function getMachineDisksOutput(args: GetMachineDisksOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetMachineDisksResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("talos:index/getMachineDisks:getMachineDisks", {
        "clientConfiguration": args.clientConfiguration,
        "endpoint": args.endpoint,
        "filters": args.filters,
        "node": args.node,
        "timeouts": args.timeouts,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getMachineDisks.
 */
export interface GetMachineDisksOutputArgs {
    clientConfiguration: pulumi.Input<inputs.GetMachineDisksClientConfigurationArgs>;
    endpoint?: pulumi.Input<string>;
    filters?: pulumi.Input<inputs.GetMachineDisksFiltersArgs>;
    node: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.GetMachineDisksTimeoutsArgs>;
}
