// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class MachineSecrets extends pulumi.CustomResource {
    /**
     * Get an existing MachineSecrets resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: MachineSecretsState, opts?: pulumi.CustomResourceOptions): MachineSecrets {
        return new MachineSecrets(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'talos:index/machineSecrets:MachineSecrets';

    /**
     * Returns true if the given object is an instance of MachineSecrets.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MachineSecrets {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === MachineSecrets.__pulumiType;
    }

    /**
     * The generated client configuration data
     */
    public /*out*/ readonly clientConfiguration!: pulumi.Output<outputs.MachineSecretsClientConfiguration>;
    /**
     * The secrets for the talos cluster
     */
    public /*out*/ readonly machineSecrets!: pulumi.Output<outputs.MachineSecretsMachineSecrets>;
    /**
     * The version of talos features to use in generated machine configuration
     */
    public readonly talosVersion!: pulumi.Output<string>;

    /**
     * Create a MachineSecrets resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: MachineSecretsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: MachineSecretsArgs | MachineSecretsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as MachineSecretsState | undefined;
            resourceInputs["clientConfiguration"] = state ? state.clientConfiguration : undefined;
            resourceInputs["machineSecrets"] = state ? state.machineSecrets : undefined;
            resourceInputs["talosVersion"] = state ? state.talosVersion : undefined;
        } else {
            const args = argsOrState as MachineSecretsArgs | undefined;
            resourceInputs["talosVersion"] = args ? args.talosVersion : undefined;
            resourceInputs["clientConfiguration"] = undefined /*out*/;
            resourceInputs["machineSecrets"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(MachineSecrets.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering MachineSecrets resources.
 */
export interface MachineSecretsState {
    /**
     * The generated client configuration data
     */
    clientConfiguration?: pulumi.Input<inputs.MachineSecretsClientConfiguration>;
    /**
     * The secrets for the talos cluster
     */
    machineSecrets?: pulumi.Input<inputs.MachineSecretsMachineSecrets>;
    /**
     * The version of talos features to use in generated machine configuration
     */
    talosVersion?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a MachineSecrets resource.
 */
export interface MachineSecretsArgs {
    /**
     * The version of talos features to use in generated machine configuration
     */
    talosVersion?: pulumi.Input<string>;
}
