# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: observability
spec:
  interval: 30m
  timeout: 10m
  chartRef:
    kind: OCIRepository
    name: victoria-metrics-k8s-stack
    namespace: observability
  maxHistory: 3
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    grafana:
      initChownData:
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
          seccompProfile: { type: RuntimeDefault }
      sidecar:
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
          seccompProfile: { type: RuntimeDefault }
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
      persistence:
        enabled: true
        storageClassName: &storageClassName nas
        size: 2Gi
    vmsingle:
      enabled: true

    alertmanager:
      config:
        route:
          receiver: "discord-infra"
          group_by: ["alertgroup", "job"]
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 4h

        receivers:
          - name: "discord-infra"
            discord_configs:
              - webhook_url: 'replacedfromvalues'
                username: 'CRITICAL ALERT'
                avatar_url: 'https://cdn-icons-png.flaticon.com/512/564/564619.png'
                title: '🚨 CRITICAL ALERT'
                message: '@everyone **CRITICAL ISSUE DETECTED!**'
                embed:
                  title: 'Critical Service Alert'
                  description: |
                    {{ range .Alerts }}
                    🔥 **{{ .Labels.name }}** is {{ .Labels.severity | upper }}
                    📋 **Details:** {{ .Annotations.description }}
                    ⏰ **Started:** {{ .StartsAt.Format "15:04:05" }}
                    {{ end }}
                  color: 16711680  # Red color
                  footer:
                    text: 'Homelab Monitoring'
                  timestamp: '{{ .Alerts.Firing | first | index 0 | index "StartsAt" }}'
  valuesFrom:
    - kind: Secret
      name: discord-webhook
      valuesKey: token
      targetPath: alertmanager.config.receivers[0].discord_configs[0].webhook_url
