apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ocirepository.yaml
  - helmrelease.yaml
  - httproute.yaml
  - blackbox-ocirepository.yaml
  - blackbox-helmrelease.yaml
