# https://taskfile.dev

version: '3'

includes:
  proxmox:
    taskfile: ./bootstrap/proxmox
    dir: ./bootstrap/proxmox

tasks:
  default:
    cmds:
      - task: proxmox:default
        vars:
          CLI_ARGS: apply
#      - task: kubernetes-bootstrap

  replace-kubernetes:
    cmds:
      - task: proxmox:default
        vars:
          CLI_ARGS: |
            apply -replace='proxmox_virtual_environment_vm.controlplane[0]' \
              -replace='proxmox_virtual_environment_vm.controlplane[1]' \
              -replace='proxmox_virtual_environment_vm.controlplane[2]'

  replace-matchbox:
    cmds:
      - task: default
      - task: replace-kubernetes

  kubernetes-bootstrap:
    cmds:
      - kubectl get ns flux-system || kubectl create ns flux-system
      - |
        kubectl -n flux-system get secret sops-age || kubectl create secret generic sops-age \
          --namespace=flux-system \
          --from-literal=age.agekey="$(infisical secrets get TF_VAR_SOPS_AGEKEY --env=prod --projectId=201b912b-40de-44bf-bb83-ab1bc77554b7 --plain)"
      - |
        infisical run --env=prod --projectId=201b912b-40de-44bf-bb83-ab1bc77554b7 -- flux bootstrap github \
          --context=kubernetes-admin-cluster.local@cluster.local \
          --owner=navaneeth-dev \
          --repository=fluxcd-homelab \
          --branch=main \
          --personal \
          --path=k8s/clusters/kubespray
