# https://taskfile.dev

version: '3'

tasks:
  apply-config:
    dir: ./bootstrap/talos
    cmds:
      - talhelper gencommand apply | zsh

  genconfig:
    dir: ./bootstrap/talos
    cmds:
      - talhelper genconfig

  kubeconfig:
    dir: ./bootstrap/talos
    cmds:
      - talosctl -n 192.168.3.200 kubeconfig ../../ --force
      - |
        helm upgrade --install \
          cilium \
          cilium/cilium \
          --version 1.18.4 \
          --namespace kube-system \
          --set ipam.mode=kubernetes \
          --set kubeProxyReplacement=true \
          --set securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}" \
          --set securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}" \
          --set cgroup.autoMount.enabled=false \
          --set cgroup.hostRoot=/sys/fs/cgroup \
          --set k8sServiceHost=localhost \
          --set k8sServicePort=7445 \
          --set envoy.enabled=false \
          --set routingMode=native \
          --set autoDirectNodeRoutes=true \
          --set ipv4NativeRoutingCIDR="10.244.0.0/16" \
          --set endpointRoutes.enabled=true \
          --set bpf.masquerade=true
      - cilium status --wait

  bootstrap-flux:
    cmds:
      - kubectl get ns flux-system || kubectl create ns flux-system
      - |
        kubectl -n flux-system get secret sops-age || kubectl create secret generic sops-age \
          --namespace=flux-system \
          --from-literal=age.agekey="$(infisical secrets get TF_VAR_SOPS_AGEKEY --env=prod --projectId=201b912b-40de-44bf-bb83-ab1bc77554b7 --plain)"
      - |
        infisical run --env=prod --projectId=201b912b-40de-44bf-bb83-ab1bc77554b7 -- flux bootstrap github \
          --context=admin@home-cluster \
          --owner=navaneeth-dev \
          --repository=fluxcd-homelab \
          --branch=main \
          --personal \
          --path=k8s/clusters/primary
