# https://taskfile.dev

version: '3'

includes:
  proxmox:
    taskfile: ./bootstrap/proxmox
    dir: ./bootstrap/proxmox

tasks:
  default:
    cmds:
      - task: proxmox:default
        vars:
          CLI_ARGS: apply
      - task: kubespray
      - task: kubernetes-bootstrap

  upgrade:
    dir: bootstrap/kubespray
    cmds:
      - |
        kubespray-venv/bin/ansible-playbook -i ../inventory/inventory.ini upgrade-cluster.yml \
          -b -v -e system_upgrade=true -e system_upgrade_reboot=always

  kubernetes-bootstrap:
    cmds:
      - kubectl get ns flux-system || kubectl create ns flux-system
      - |
        kubectl -n flux-system get secret sops-age || kubectl create secret generic sops-age \
          --namespace=flux-system \
          --from-literal=age.agekey="$(infisical secrets get TF_VAR_SOPS_AGEKEY --env=prod --projectId=201b912b-40de-44bf-bb83-ab1bc77554b7 --plain)"
      - |
        infisical run --env=prod --projectId=201b912b-40de-44bf-bb83-ab1bc77554b7 -- flux bootstrap github \
          --context=kubernetes-admin-cluster.local@cluster.local \
          --owner=navaneeth-dev \
          --repository=fluxcd-homelab \
          --branch=main \
          --personal \
          --path=k8s/clusters/kubespray

  kubespray:
    dir: bootstrap/kubespray
    cmds:
      - kubespray-venv/bin/ansible-playbook -i ../inventory/inventory.ini cluster.yml -b -v

  kubespray-reset:
    dir: bootstrap/kubespray
    cmds:
      - kubespray-venv/bin/ansible-playbook -i ../inventory/inventory.ini reset.yml -b -v

  install:
    dir: bootstrap/kubespray
    cmds:
      - python3 -m venv kubespray-venv
      - kubespray-venv/bin/pip3 install -r requirements.txt