# https://taskfile.dev

version: '3'

includes:
  proxmox:
    taskfile: ./bootstrap/proxmox
    dir: ./bootstrap/proxmox

tasks:
  default:
    cmds:
      - task: proxmox:default
        vars:
          CLI_ARGS: apply
#      - task: kubespray

  kubespray:
    dir: bootstrap/kubespray
    cmds:
      - ansible-playbook -i ../inventory/inventory.ini cluster.yml -b -v
