# https://taskfile.dev

version: '3'

includes:
  proxmox:
    taskfile: ./bootstrap/proxmox
    dir: ./bootstrap/proxmox

tasks:
  default:
    cmds:
      - task: proxmox:default
        vars:
          CLI_ARGS: apply
#      - task: kubernetes-bootstrap

  genconfig:
    dir: ./bootstrap/talos
    cmds:
      - talhelper genconfig

  kubeconfig:
    dir: ./bootstrap/talos
    cmds:
      - talosctl -n 192.168.3.2 bootstrap
      - sleep 15
      - talosctl -n 192.168.3.200 kubeconfig ../../ --force

  replace-kubernetes:
    cmds:
      - task: genconfig
      - task: proxmox:default
        vars:
          CLI_ARGS: |
            apply -replace='proxmox_virtual_environment_vm.controlplane[0]' \
              -replace='proxmox_virtual_environment_vm.controlplane[1]' \
              -replace='proxmox_virtual_environment_vm.controlplane[2]' \
              -replace='proxmox_virtual_environment_file.talos_config[0]' \
              -replace='proxmox_virtual_environment_file.talos_config[1]' \
              -replace='proxmox_virtual_environment_file.talos_config[2]'
      - sleep 5
      - task: kubeconfig
      - kubectl get nodes

  replace-matchbox:
    cmds:
      - task: proxmox:default
        vars:
          CLI_ARGS: |
            apply -replace='proxmox_virtual_environment_vm.controlplane[0]' \
              -replace='proxmox_virtual_environment_vm.controlplane[1]' \
              -replace='proxmox_virtual_environment_vm.controlplane[2]' \
              -replace='proxmox_virtual_environment_vm.omni'

  kubernetes-bootstrap:
    cmds:
      - kubectl get ns flux-system || kubectl create ns flux-system
      - |
        kubectl -n flux-system get secret sops-age || kubectl create secret generic sops-age \
          --namespace=flux-system \
          --from-literal=age.agekey="$(infisical secrets get TF_VAR_SOPS_AGEKEY --env=prod --projectId=201b912b-40de-44bf-bb83-ab1bc77554b7 --plain)"
      - |
        infisical run --env=prod --projectId=201b912b-40de-44bf-bb83-ab1bc77554b7 -- flux bootstrap github \
          --context=admin@home-cluster \
          --owner=navaneeth-dev \
          --repository=fluxcd-homelab \
          --branch=main \
          --personal \
          --path=k8s/clusters/kubespray
