# https://taskfile.dev

version: '3'

includes:
  proxmox:
    taskfile: ./bootstrap/proxmox
    dir: ./bootstrap/proxmox

tasks:
  default:
    cmds:
      - task: proxmox:default
        vars:
          CLI_ARGS: apply
#      - task: kubernetes-bootstrap

  genconfig:
    dir: ./bootstrap/talos
    cmds:
      - talhelper genconfig

  kubeconfig:
    dir: ./bootstrap/talos
    cmds:
      - talosctl -n 192.168.3.2 bootstrap
      - echo Wait for Kubernetes nodes && sleep 300
      - talosctl -n 192.168.3.200 kubeconfig ../../ --force
      - |
        helm install \
          cilium \
          cilium/cilium \
          --version 1.18.0 \
          --namespace kube-system \
          --set ipam.mode=kubernetes \
          --set kubeProxyReplacement=true \
          --set securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}" \
          --set securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}" \
          --set cgroup.autoMount.enabled=false \
          --set cgroup.hostRoot=/sys/fs/cgroup \
          --set k8sServiceHost=localhost \
          --set k8sServicePort=7445
      - cilium status --wait

  replace-kubernetes:
    cmds:
      - task: genconfig
      - task: proxmox:default
        vars:
          CLI_ARGS: |
            apply -replace='proxmox_virtual_environment_vm.controlplane[0]' \
              -replace='proxmox_virtual_environment_vm.controlplane[1]' \
              -replace='proxmox_virtual_environment_vm.controlplane[2]' \
              -replace='proxmox_virtual_environment_file.talos_config[0]' \
              -replace='proxmox_virtual_environment_file.talos_config[1]' \
              -replace='proxmox_virtual_environment_file.talos_config[2]'
      - sleep 30
      - task: kubeconfig

  replace-matchbox:
    cmds:
      - task: proxmox:default
        vars:
          CLI_ARGS: |
            apply -replace='proxmox_virtual_environment_vm.controlplane[0]' \
              -replace='proxmox_virtual_environment_vm.controlplane[1]' \
              -replace='proxmox_virtual_environment_vm.controlplane[2]' \
              -replace='proxmox_virtual_environment_vm.omni'

  bootstrap:flux:
    cmds:
      - kubectl get ns flux-system || kubectl create ns flux-system
      - |
        kubectl -n flux-system get secret sops-age || kubectl create secret generic sops-age \
          --namespace=flux-system \
          --from-literal=age.agekey="$(infisical secrets get TF_VAR_SOPS_AGEKEY --env=prod --projectId=201b912b-40de-44bf-bb83-ab1bc77554b7 --plain)"
      - |
        infisical run --env=prod --projectId=201b912b-40de-44bf-bb83-ab1bc77554b7 -- flux bootstrap github \
          --context=admin@home-cluster \
          --owner=navaneeth-dev \
          --repository=fluxcd-homelab \
          --branch=main \
          --personal \
          --path=k8s/clusters/kubespray
