# https://taskfile.dev

version: '3'

includes:
  proxmox:
    taskfile: ./bootstrap/proxmox
    dir: ./bootstrap/proxmox

tasks:
  default:
    cmds:
      - task: proxmox:default
        vars:
          CLI_ARGS: apply
      - task: kubespray

  kubespray:
    dir: bootstrap/kubespray
    cmds:
      - kubespray-venv/bin/ansible-playbook -i ../inventory/inventory.ini cluster.yml -b -v

  install:
    dir: bootstrap/kubespray
    cmds:
      - python3 -m venv kubespray-venv
      - kubespray-venv/bin/pip3 install -r requirements.txt