apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name librespeed
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
    spec:
      containers:
        - name: *name
          image: ghcr.io/librespeed/speedtest:latest@sha256:96eeeb4bad3d25f46636bef672eebf52a34ac967c6cd66644294cc585ab799b9
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "100m"
              memory: "512Mi"
