kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: librespeed
spec:
  interval: 60s
  module: http_2xx
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - https://example.com