apiVersion: v1
kind: Service
metadata:
  name: &name librespeed
  namespace: homelab
spec:
  type: ClusterIP
  ports:
    - name: *name
      port: 8080
      targetPort: 8080
  selector:
    app: *name
