apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name qbittorrent
  namespace: homelab
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      *name:
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile: { type: RuntimeDefault }
        containers:
          app:
            image:
              repository: ghcr.io/hotio/qbittorrent
              tag: release-5.1.2
            env:
              TZ: "${TZ}"
              PUID: 1000
              GUID: 1000
              WEBUI_PORTS: "8080/tcp,8080/udp"
              LIBTORRENT: "v1"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                memory: 500Mi
    service:
      app:
        primary: true
        controller: *name
        ports:
          http:
            port: 8080

    persistence:
      config:
        enabled: true
        type: nfs
        server: "nas.home.arpa"
        path: "/srv/nfs4/config/qbittorrent"
        globalMounts:
          - path: /config
      data:
        enabled: true
        type: nfs
        server: "nas.home.arpa"
        path: "/srv/nfs4/data"
        globalMounts:
          - path: /data
            readOnly: true
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
