apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: arr-stack
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arr-stack
  template:
    metadata:
      labels:
        app: arr-stack
    spec:
      containers:
        - name: sabnzbd
          image: ghcr.io/hotio/sabnzbd@sha256:aff501a8144b64f8bd318768e37987d7d6c02c41b95917519343eb960c41ae0a
          ports:
            - containerPort: 8080
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Asia/Kolkata"
            - name: WEBUI_PORTS
              value: "8080/tcp,8080/udp"
          volumeMounts:
            - name: sabnzbd-config
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: data
          nfs:
            server: 'nas.home.arpa'
            path: "/srv/nfs4/data"
        - name: sabnzbd-config
          nfs:
            server: "nas2.home.arpa"
            path: "/config/sabnzbd"
