- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade system
  become: true
  ansible.builtin.apt:
    upgrade: full
    autoclean: true
    autoremove: true

- name: Check if reboot is required
  become: true
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot if required
  become: true
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible after upgrade"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
  when: reboot_required.stat.exists
