apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kube-prometheus-stack
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
    - name: https
      protocol: HTTP
      port: 443
