# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
  dependsOn:
    - name: nfs-subdir-external-provisioner
      namespace: nfs-subdir-external-provisioner
  install:
    crds: CreateReplace
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace
    force: true
  test:
    enable: true
  rollback:
    recreate: true
    force: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  driftDetection:
    mode: enabled
  maxHistory: 3
  timeout: 30m
  values:
    grafana:
      initChownData:
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
          seccompProfile: { type: RuntimeDefault }
      sidecar:
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
          seccompProfile: { type: RuntimeDefault }
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
      persistence:
        enabled: true
        storageClassName: &storageClassName nas
        size: 10Gi
      # Provision grafana-dashboards-kubernetes
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: 'grafana-dashboards-kubernetes'
              orgId: 1
              folder: 'Kubernetes'
              type: file
              disableDeletion: true
              editable: true
              options:
                path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
      dashboards:
        grafana-dashboards-kubernetes:
          k8s-views-global:
            url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
            token: ''
      route:
        main:
          enabled: true

          # -- Set the route apiVersion, e.g. gateway.networking.k8s.io/v1 or gateway.networking.k8s.io/v1alpha2
          apiVersion: gateway.networking.k8s.io/v1
          kind: HTTPRoute

          hostnames:
            - grafana.proxy.home.arpa
          parentRefs:
            - name: eg

          # -- create http route for redirect (https://gateway-api.sigs.k8s.io/guides/http-redirect-rewrite/#http-to-https-redirects)
          ## Take care that you only enable this on the http listener of the gateway to avoid an infinite redirect.
          ## matches, filters and additionalRules will be ignored if this is set to true. Be are
          httpsRedirect: false

          matches:
            - path:
                type: PathPrefix
                value: /

    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: *storageClassName
              resources:
                requests:
                  storage: 50Gi

      route:
        main:
          enabled: true

          # -- Set the route apiVersion, e.g. gateway.networking.k8s.io/v1 or gateway.networking.k8s.io/v1alpha2
          apiVersion: gateway.networking.k8s.io/v1
          kind: HTTPRoute

          hostnames:
            - prometheus.proxy.home.arpa
          parentRefs:
            - name: eg

          # -- create http route for redirect (https://gateway-api.sigs.k8s.io/guides/http-redirect-rewrite/#http-to-https-redirects)
          ## Take care that you only enable this on the http listener of the gateway to avoid an infinite redirect.
          ## matches, filters and additionalRules will be ignored if this is set to true. Be are
          httpsRedirect: false

          matches:
            - path:
                type: PathPrefix
                value: /

    kubeProxy:
      enabled: false
