apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - namespace.yaml
  - gateway.yaml
  - ocirepository.yaml
  - blackbox-ocirepository.yaml
  - helmrelease.yaml
  - blackbox-helmrelease.yaml
