---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  docker.yaml: ""

  kubernetes.yaml: |
    mode: disabled
    gateway: false
    ingress: false
    traefik: false

  settings.yaml: |
    title: Homelab
    theme: dark
    color: slate
    headerStyle: clean
    statusStyle: dot
    useEqualHeights: false
    fiveColumns: true
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
    layout:
      Media:
        style: row
        columns: 4

  widgets.yaml: |
    - search:
        provider: duckduckgo
        focus: false
        target: _blank

  bookmarks.yaml: ""

  services.yaml: |
    - Media:
        - Jellyfin:
            href: 'https://jellyfin.${DOMAIN}'
            icon: jellyfin.svg
        - Radarr:
            href: 'https://radarr.${DOMAIN}'
            icon: radarr.svg
        - Sonarr:
            href: 'https://sonarr.${DOMAIN}'
            icon: sonarr.svg
