---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  docker.yaml: ""

  kubernetes.yaml: |
    mode: disabled
    gateway: false
    ingress: false
    traefik: false

  settings.yaml: |
    title: Homelab
    # background:
    #   image: https://raw.githubusercontent.com/joryirving/home-ops/main/.docs/assets/101518784_p0.jpg
    #   opacity: 20
    favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/heimdall.png
    theme: dark
    color: slate
    headerStyle: clean
    statusStyle: dot
    useEqualHeights: false
    fiveColumns: true
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
    layout:
      Home Automation:
        style: column
        icon: home-assistant
      LLM/Ai:
        style: column
        icon: open-webui
      Apps:
        style: column
        icon: immich
      Security:
        style: column
        icon: pocket-id
      Social:
        style: column
        icon: mastodon
      Media:
        style: column
        icon: jellyfin
      Downloads:
        style: column
        icon: sonarr
      Kubernetes:
        style: column
        icon: kubernetes

  widgets.yaml: |
    - search:
        provider: duckduckgo
        focus: false
        target: _blank

  bookmarks.yaml: ""

  services.yaml: ""