# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name jellyfin
  namespace: homelab
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      jellyfin:
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
        containers:
          app:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.10.7@sha256:e4d1dc5374344446a3a78e43dd211247f22afba84ea2e5a13cbe1a94e1ff2141
            env:
              JELLYFIN_PublishedServerUrl: "https://jellyfin.${DOMAIN}"
              TZ: "${TZ}"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 3
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              privileged: true
#              allowPrivilegeEscalation: false
#              readOnlyRootFilesystem: true
#              capabilities: { drop: ["ALL"] }
            resources:
              limits:
                gpu.intel.com/i915: "1"
                memory: 5Gi
                cpu: 2000m
              requests:
                cpu: 1000m
                memory: 4Gi
    service:
      app:
        primary: true
        controller: *name
        ports:
          http:
            port: 8096

    route:
      main:
        enabled: true
        kind: HTTPRoute
        parentRefs:
          - kind: Gateway
            name: reverse-proxy
            namespace: envoy-gateway-system
        hostnames:
          - 'jellyfin.${DOMAIN}'

    persistence:
      config:
        enabled: true
        type: nfs
        server: "nas.home.arpa"
        path: "/srv/nfs4/config/jellyfin"
        globalMounts:
          - path: /config
      data:
        enabled: true
        type: nfs
        server: "nas.home.arpa"
        path: "/srv/nfs4/data"
        globalMounts:
          - path: /data
      nas2:
        enabled: true
        type: nfs
        server: "nas2.home.arpa"
        path: "/configs"
      tmpfs:
        type: emptyDir
        advancedMounts:
          jellyfin:
            app:
              - path: /cache
                subPath: cache
              - path: /config/log
                subPath: log
              - path: /tmp
                subPath: tmp
