# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name jellyfin
  namespace: homelab
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      *name:
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile: { type: RuntimeDefault }
        containers:
          app:
            image:
              repository: ghcr.io/hotio/jellyfin
              tag: release-10.10.7
            env:
              TZ: "${TZ}"
              PUID: 1000
              PGID: 1000
              JELLYFIN_PublishedServerUrl: "https://jellyfin.${DOMAIN}"
            securityContext:
              privileged: true
#              allowPrivilegeEscalation: false
#              readOnlyRootFilesystem: true
#              capabilities: { drop: ["ALL"] }
            resources:
              limits:
                gpu.intel.com/i915: "1"
                memory: 500Mi
              requests:
                cpu: 50m
                memory: 100Mi
    service:
      app:
        primary: true
        controller: *name
        ports:
          http:
            port: 8096

    persistence:
      config:
        enabled: true
        type: nfs
        server: "nas.home.arpa"
        path: "/srv/nfs4/config/jellyfin"
        globalMounts:
          - path: /config
      data:
        enabled: true
        type: nfs
        server: "nas.home.arpa"
        path: "/srv/nfs4/data"
        globalMounts:
          - path: /data
