apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: influxdb
spec:
  parentRefs:
    - name: reverse-proxy
      sectionName: http
  rules:
    - backendRefs:
        - name: qbittorrent-bittorrent
          port: 52525