# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: oci-cluster
talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"
endpoint: https://10.0.60.200:6443
allowSchedulingOnControlPlanes: true
additionalMachineCertSans:
  - 10.0.10.2
  - 10.0.10.2
  - 10.0.10.2
additionalApiServerCertSans:
  - 10.0.60.200
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12
cniConfig:
  name: none
nodes:
  - hostname: controlplane-pve
    ipAddress: 192.168.3.2
    controlPlane: true
    installDisk: /dev/vda
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.3.2/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.3.1
        dhcp: false
        vip:
          ip: 192.168.3.200
  - hostname: controlplane-pve-minipc
    ipAddress: 192.168.3.3
    controlPlane: true
    installDisk: /dev/vda
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.3.3/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.3.1
        dhcp: false
        vip:
          ip: 192.168.3.200
  - hostname: controlplane-pve-thinkcentre
    ipAddress: 192.168.3.4
    controlPlane: true
    installDisk: /dev/vda
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.3.4/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.3.1
        dhcp: false
        vip:
          ip: 192.168.3.200
controlPlane:
  machineSpec:
    mode: nocloud
  nameservers:
    - 192.168.3.1
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/qemu-guest-agent

patches:
  - |
    machine:
      time:
        servers:
          - 169.254.169.254

  - |
    machine:
      kubelet:
        extraArgs:
          rotate-server-certificates: true
    cluster:
      extraManifests:
        - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
        - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

  - |-
    cluster:
      proxy:
        disabled: true

  - &hostDNS |
    machine:
      features:
        hostDNS:
          enabled: true
          resolveMemberNames: true
          forwardKubeDNSToHost: false
