// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class BootstrapGit extends pulumi.CustomResource {
    /**
     * Get an existing BootstrapGit resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: BootstrapGitState, opts?: pulumi.CustomResourceOptions): BootstrapGit {
        return new BootstrapGit(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'flux:index/bootstrapGit:BootstrapGit';

    /**
     * Returns true if the given object is an instance of BootstrapGit.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is BootstrapGit {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === BootstrapGit.__pulumiType;
    }

    /**
     * The internal cluster domain. Defaults to `cluster.local`
     */
    public readonly clusterDomain!: pulumi.Output<string>;
    /**
     * Toolkit components to include in the install manifests. Defaults to `[source-controller kustomize-controller
     * helm-controller notification-controller]`
     */
    public readonly components!: pulumi.Output<string[]>;
    /**
     * List of extra components to include in the install manifests.
     */
    public readonly componentsExtras!: pulumi.Output<string[] | undefined>;
    /**
     * Delete manifests from git repository. Defaults to `true`.
     */
    public readonly deleteGitManifests!: pulumi.Output<boolean>;
    /**
     * Use the existing secret for flux controller and don't create one from bootstrap
     */
    public readonly disableSecretCreation!: pulumi.Output<boolean | undefined>;
    /**
     * When enabled, the Flux manifests will be extracted from the provider binary instead of being downloaded from GitHub.com.
     * Defaults to `false`.
     */
    public readonly embeddedManifests!: pulumi.Output<boolean>;
    /**
     * Kubernetes secret name used for pulling the toolkit images from a private registry.
     */
    public readonly imagePullSecret!: pulumi.Output<string | undefined>;
    /**
     * Interval at which to reconcile from bootstrap repository. Defaults to `1m0s`.
     */
    public readonly interval!: pulumi.Output<string>;
    /**
     * Keep the namespace after uninstalling Flux components. Defaults to `false`.
     */
    public readonly keepNamespace!: pulumi.Output<boolean>;
    /**
     * Kustomization to override configuration set by default.
     */
    public readonly kustomizationOverride!: pulumi.Output<string | undefined>;
    /**
     * Log level for toolkit components. Defaults to `info`.
     */
    public readonly logLevel!: pulumi.Output<string>;
    /**
     * The install manifests are built from a GitHub release or kustomize overlay if using a local path. Defaults to
     * `https://github.com/fluxcd/flux2/releases`.
     *
     * @deprecated Deprecated
     */
    public readonly manifestsPath!: pulumi.Output<string | undefined>;
    /**
     * The namespace scope for install manifests. Defaults to `flux-system`. It will be created if it does not exist.
     */
    public readonly namespace!: pulumi.Output<string>;
    /**
     * Deny ingress access to the toolkit controllers from other namespaces using network policies. Defaults to `true`.
     */
    public readonly networkPolicy!: pulumi.Output<boolean>;
    /**
     * Path relative to the repository root, when specified the cluster sync will be scoped to this path (immutable).
     */
    public readonly path!: pulumi.Output<string | undefined>;
    /**
     * Configures the GitRepository source to initialize and include Git submodules in the artifact it produces.
     */
    public readonly recurseSubmodules!: pulumi.Output<boolean | undefined>;
    /**
     * Container registry where the toolkit images are published. Defaults to `ghcr.io/fluxcd`.
     */
    public readonly registry!: pulumi.Output<string>;
    /**
     * Container registry credentials in the format 'user:password'
     */
    public readonly registryCredentials!: pulumi.Output<string | undefined>;
    /**
     * Git repository files created and managed by the provider.
     */
    public /*out*/ readonly repositoryFiles!: pulumi.Output<{[key: string]: string}>;
    /**
     * Name of the secret the sync credentials can be found in or stored to. Defaults to `flux-system`.
     */
    public readonly secretName!: pulumi.Output<string>;
    public readonly timeouts!: pulumi.Output<outputs.BootstrapGitTimeouts | undefined>;
    /**
     * List of toleration keys used to schedule the components pods onto nodes with matching taints.
     */
    public readonly tolerationKeys!: pulumi.Output<string[] | undefined>;
    /**
     * Flux version. Defaults to `v2.6.4`. Has no effect when `embedded_manifests` is enabled.
     */
    public readonly version!: pulumi.Output<string>;
    /**
     * If true watch for custom resources in all namespaces. Defaults to `true`.
     */
    public readonly watchAllNamespaces!: pulumi.Output<boolean>;

    /**
     * Create a BootstrapGit resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: BootstrapGitArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: BootstrapGitArgs | BootstrapGitState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as BootstrapGitState | undefined;
            resourceInputs["clusterDomain"] = state ? state.clusterDomain : undefined;
            resourceInputs["components"] = state ? state.components : undefined;
            resourceInputs["componentsExtras"] = state ? state.componentsExtras : undefined;
            resourceInputs["deleteGitManifests"] = state ? state.deleteGitManifests : undefined;
            resourceInputs["disableSecretCreation"] = state ? state.disableSecretCreation : undefined;
            resourceInputs["embeddedManifests"] = state ? state.embeddedManifests : undefined;
            resourceInputs["imagePullSecret"] = state ? state.imagePullSecret : undefined;
            resourceInputs["interval"] = state ? state.interval : undefined;
            resourceInputs["keepNamespace"] = state ? state.keepNamespace : undefined;
            resourceInputs["kustomizationOverride"] = state ? state.kustomizationOverride : undefined;
            resourceInputs["logLevel"] = state ? state.logLevel : undefined;
            resourceInputs["manifestsPath"] = state ? state.manifestsPath : undefined;
            resourceInputs["namespace"] = state ? state.namespace : undefined;
            resourceInputs["networkPolicy"] = state ? state.networkPolicy : undefined;
            resourceInputs["path"] = state ? state.path : undefined;
            resourceInputs["recurseSubmodules"] = state ? state.recurseSubmodules : undefined;
            resourceInputs["registry"] = state ? state.registry : undefined;
            resourceInputs["registryCredentials"] = state ? state.registryCredentials : undefined;
            resourceInputs["repositoryFiles"] = state ? state.repositoryFiles : undefined;
            resourceInputs["secretName"] = state ? state.secretName : undefined;
            resourceInputs["timeouts"] = state ? state.timeouts : undefined;
            resourceInputs["tolerationKeys"] = state ? state.tolerationKeys : undefined;
            resourceInputs["version"] = state ? state.version : undefined;
            resourceInputs["watchAllNamespaces"] = state ? state.watchAllNamespaces : undefined;
        } else {
            const args = argsOrState as BootstrapGitArgs | undefined;
            resourceInputs["clusterDomain"] = args ? args.clusterDomain : undefined;
            resourceInputs["components"] = args ? args.components : undefined;
            resourceInputs["componentsExtras"] = args ? args.componentsExtras : undefined;
            resourceInputs["deleteGitManifests"] = args ? args.deleteGitManifests : undefined;
            resourceInputs["disableSecretCreation"] = args ? args.disableSecretCreation : undefined;
            resourceInputs["embeddedManifests"] = args ? args.embeddedManifests : undefined;
            resourceInputs["imagePullSecret"] = args ? args.imagePullSecret : undefined;
            resourceInputs["interval"] = args ? args.interval : undefined;
            resourceInputs["keepNamespace"] = args ? args.keepNamespace : undefined;
            resourceInputs["kustomizationOverride"] = args ? args.kustomizationOverride : undefined;
            resourceInputs["logLevel"] = args ? args.logLevel : undefined;
            resourceInputs["manifestsPath"] = args ? args.manifestsPath : undefined;
            resourceInputs["namespace"] = args ? args.namespace : undefined;
            resourceInputs["networkPolicy"] = args ? args.networkPolicy : undefined;
            resourceInputs["path"] = args ? args.path : undefined;
            resourceInputs["recurseSubmodules"] = args ? args.recurseSubmodules : undefined;
            resourceInputs["registry"] = args ? args.registry : undefined;
            resourceInputs["registryCredentials"] = args ? args.registryCredentials : undefined;
            resourceInputs["secretName"] = args ? args.secretName : undefined;
            resourceInputs["timeouts"] = args ? args.timeouts : undefined;
            resourceInputs["tolerationKeys"] = args ? args.tolerationKeys : undefined;
            resourceInputs["version"] = args ? args.version : undefined;
            resourceInputs["watchAllNamespaces"] = args ? args.watchAllNamespaces : undefined;
            resourceInputs["repositoryFiles"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(BootstrapGit.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering BootstrapGit resources.
 */
export interface BootstrapGitState {
    /**
     * The internal cluster domain. Defaults to `cluster.local`
     */
    clusterDomain?: pulumi.Input<string>;
    /**
     * Toolkit components to include in the install manifests. Defaults to `[source-controller kustomize-controller
     * helm-controller notification-controller]`
     */
    components?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * List of extra components to include in the install manifests.
     */
    componentsExtras?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Delete manifests from git repository. Defaults to `true`.
     */
    deleteGitManifests?: pulumi.Input<boolean>;
    /**
     * Use the existing secret for flux controller and don't create one from bootstrap
     */
    disableSecretCreation?: pulumi.Input<boolean>;
    /**
     * When enabled, the Flux manifests will be extracted from the provider binary instead of being downloaded from GitHub.com.
     * Defaults to `false`.
     */
    embeddedManifests?: pulumi.Input<boolean>;
    /**
     * Kubernetes secret name used for pulling the toolkit images from a private registry.
     */
    imagePullSecret?: pulumi.Input<string>;
    /**
     * Interval at which to reconcile from bootstrap repository. Defaults to `1m0s`.
     */
    interval?: pulumi.Input<string>;
    /**
     * Keep the namespace after uninstalling Flux components. Defaults to `false`.
     */
    keepNamespace?: pulumi.Input<boolean>;
    /**
     * Kustomization to override configuration set by default.
     */
    kustomizationOverride?: pulumi.Input<string>;
    /**
     * Log level for toolkit components. Defaults to `info`.
     */
    logLevel?: pulumi.Input<string>;
    /**
     * The install manifests are built from a GitHub release or kustomize overlay if using a local path. Defaults to
     * `https://github.com/fluxcd/flux2/releases`.
     *
     * @deprecated Deprecated
     */
    manifestsPath?: pulumi.Input<string>;
    /**
     * The namespace scope for install manifests. Defaults to `flux-system`. It will be created if it does not exist.
     */
    namespace?: pulumi.Input<string>;
    /**
     * Deny ingress access to the toolkit controllers from other namespaces using network policies. Defaults to `true`.
     */
    networkPolicy?: pulumi.Input<boolean>;
    /**
     * Path relative to the repository root, when specified the cluster sync will be scoped to this path (immutable).
     */
    path?: pulumi.Input<string>;
    /**
     * Configures the GitRepository source to initialize and include Git submodules in the artifact it produces.
     */
    recurseSubmodules?: pulumi.Input<boolean>;
    /**
     * Container registry where the toolkit images are published. Defaults to `ghcr.io/fluxcd`.
     */
    registry?: pulumi.Input<string>;
    /**
     * Container registry credentials in the format 'user:password'
     */
    registryCredentials?: pulumi.Input<string>;
    /**
     * Git repository files created and managed by the provider.
     */
    repositoryFiles?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Name of the secret the sync credentials can be found in or stored to. Defaults to `flux-system`.
     */
    secretName?: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.BootstrapGitTimeouts>;
    /**
     * List of toleration keys used to schedule the components pods onto nodes with matching taints.
     */
    tolerationKeys?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Flux version. Defaults to `v2.6.4`. Has no effect when `embedded_manifests` is enabled.
     */
    version?: pulumi.Input<string>;
    /**
     * If true watch for custom resources in all namespaces. Defaults to `true`.
     */
    watchAllNamespaces?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a BootstrapGit resource.
 */
export interface BootstrapGitArgs {
    /**
     * The internal cluster domain. Defaults to `cluster.local`
     */
    clusterDomain?: pulumi.Input<string>;
    /**
     * Toolkit components to include in the install manifests. Defaults to `[source-controller kustomize-controller
     * helm-controller notification-controller]`
     */
    components?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * List of extra components to include in the install manifests.
     */
    componentsExtras?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Delete manifests from git repository. Defaults to `true`.
     */
    deleteGitManifests?: pulumi.Input<boolean>;
    /**
     * Use the existing secret for flux controller and don't create one from bootstrap
     */
    disableSecretCreation?: pulumi.Input<boolean>;
    /**
     * When enabled, the Flux manifests will be extracted from the provider binary instead of being downloaded from GitHub.com.
     * Defaults to `false`.
     */
    embeddedManifests?: pulumi.Input<boolean>;
    /**
     * Kubernetes secret name used for pulling the toolkit images from a private registry.
     */
    imagePullSecret?: pulumi.Input<string>;
    /**
     * Interval at which to reconcile from bootstrap repository. Defaults to `1m0s`.
     */
    interval?: pulumi.Input<string>;
    /**
     * Keep the namespace after uninstalling Flux components. Defaults to `false`.
     */
    keepNamespace?: pulumi.Input<boolean>;
    /**
     * Kustomization to override configuration set by default.
     */
    kustomizationOverride?: pulumi.Input<string>;
    /**
     * Log level for toolkit components. Defaults to `info`.
     */
    logLevel?: pulumi.Input<string>;
    /**
     * The install manifests are built from a GitHub release or kustomize overlay if using a local path. Defaults to
     * `https://github.com/fluxcd/flux2/releases`.
     *
     * @deprecated Deprecated
     */
    manifestsPath?: pulumi.Input<string>;
    /**
     * The namespace scope for install manifests. Defaults to `flux-system`. It will be created if it does not exist.
     */
    namespace?: pulumi.Input<string>;
    /**
     * Deny ingress access to the toolkit controllers from other namespaces using network policies. Defaults to `true`.
     */
    networkPolicy?: pulumi.Input<boolean>;
    /**
     * Path relative to the repository root, when specified the cluster sync will be scoped to this path (immutable).
     */
    path?: pulumi.Input<string>;
    /**
     * Configures the GitRepository source to initialize and include Git submodules in the artifact it produces.
     */
    recurseSubmodules?: pulumi.Input<boolean>;
    /**
     * Container registry where the toolkit images are published. Defaults to `ghcr.io/fluxcd`.
     */
    registry?: pulumi.Input<string>;
    /**
     * Container registry credentials in the format 'user:password'
     */
    registryCredentials?: pulumi.Input<string>;
    /**
     * Name of the secret the sync credentials can be found in or stored to. Defaults to `flux-system`.
     */
    secretName?: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.BootstrapGitTimeouts>;
    /**
     * List of toleration keys used to schedule the components pods onto nodes with matching taints.
     */
    tolerationKeys?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Flux version. Defaults to `v2.6.4`. Has no effect when `embedded_manifests` is enabled.
     */
    version?: pulumi.Input<string>;
    /**
     * If true watch for custom resources in all namespaces. Defaults to `true`.
     */
    watchAllNamespaces?: pulumi.Input<boolean>;
}
