apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab
spec:
  secretName: homelab-cert-private-keys
  dnsNames:
    - '${DOMAIN}'
    - '*.${DOMAIN}'
  issuerRef:
    name: homelab
    kind: ClusterIssuer