---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab
  namespace: homelab
spec:
  secretName: homelab
  dnsNames:
    - '${DOMAIN}'
    - '*.${DOMAIN}'
  issuerRef:
    name: cloudflare-issuer
    kind: Issuer

