apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/intel/intel-device-plugins-for-kubernetes/tree/main/deployments/nfd?ref=v0.32.1
  - https://github.com/intel/intel-device-plugins-for-kubernetes/tree/main/deployments/nfd/overlays/node-feature-rules?ref=v0.32.1
  - https://github.com/intel/intel-device-plugins-for-kubernetes/tree/main/deployments/gpu_plugin/overlays/nfd_labeled_nodes?ref=v0.32.1
