repositories:
  - name: cilium
    url: https://helm.cilium.io/

releases:
  - name: cilium
    namespace: kube-system
    chart: cilium/cilium
    set:
      - name: devices
        value: eth0
      - name: loadBalancer.l7.backend
        value: envoy
      - name: ingressController.enabled
        value: true
      - name: ingressController.loadbalancerMode
        value: shared
      - name: ingressController.default
        value: true
      - name: l2announcements.enabled
        value: true
      - name: k8sClientRateLimit.qps
        value: 10
      - name: k8sClientRateLimit.burst
        value: 15
      - name: ipam.mode
        value: kubernetes
      - name: kubeProxyReplacement
        value: true
      - name: securityContext.capabilities.ciliumAgent
        values:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
      - name: securityContext.capabilities.cleanCiliumState
        values:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
      - name: cgroup.autoMount.enabled
        value: false
      - name: cgroup.hostRoot
        value: /sys/fs/cgroup
      - name: k8sServiceHost
        value: localhost
      - name: k8sServicePort
        value: 7445
