# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - terraform apply -auto-approve
      - terraform output -raw kubeconfig > ../kubeconfig
      - terraform output -raw talosconfig > ../talosconfig
      - helmfile init
      - helmfile apply
      - cilium status --wait
    silent: true
