apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium-ip-pool.yaml
  - cilium-l2-announcement-policy.yaml
patches:
  - target:
      kind: Service
      name: cilium-ingress
      namespace: kube-system
    patch: |-
      - op: replace
        path: /spec/ipFamilyPolicy
        value: RequireDualStack
