apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
  - ../base/arr-stack
  - ../base/librespeed
  - ../base/jellyseerr
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
