apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - envoyproxy.yaml
  - gateway-class.yaml
  - gateway.yaml
  - ocirepository.yaml
  - helmrelease.yaml
  - vmpodscrape.yaml
  - clienttrafficpolicy.yaml
