apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - gateway-class.yaml
  - gateway.yaml
  - ocirepository.yaml
  - ocirepository-addon.yaml
  - helmrelease.yaml
  - helmrelease-addon.yaml
