apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: envoy-gateway-controller
  namespace: envoy-gateway-system
spec:
  selector:
    matchLabels:
      control-plane: envoy-gateway
      app.kubernetes.io/instance: eg
  endpoints:
    - port: "19001"
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - envoy-gateway-system
